const genres = [
  { name: 'pop' },
  { name: 'pop rap' },
  { name: 'rap' },
  { name: 'tropical house' },
  { name: 'dance pop' },
  { name: 'post-teen pop' },
  { name: 'rock' },
  { name: 'trap music' },
  { name: 'hip hop' },
  { name: 'southern hip hop' },
  { name: 'latin' },
  { name: 'pop rock' },
  { name: 'dwn trap' },
  { name: 'edm' },
  { name: 'neo mellow' },
  { name: 'alternative rock' },
  { name: 'r&b' },
  { name: 'classic rock' },
  { name: 'latin pop' },
  { name: 'album rock' },
  { name: 'indie pop' },
  { name: 'alternative metal' },
  { name: 'indie rock' },
  { name: 'mellow gold' },
  { name: 'post-grunge' },
  { name: 'viral pop' },
  { name: 'hard rock' },
  { name: 'singer-songwriter' },
  { name: 'indie r&b' },
  { name: 'pop punk' },
  { name: 'folk-pop' },
  { name: 'soft rock' },
  { name: 'tropical' },
  { name: 'reggaeton' },
  { name: 'indie folk' },
  { name: 'indietronica' },
  { name: 'electro house' },
  { name: 'nu metal' },
  { name: 'permanent wave' },
  { name: 'canadian pop' },
  { name: 'gangster rap' },
  { name: 'indie poptimism' },
  { name: 'urban contemporary' },
  { name: 'contemporary country' },
  { name: 'hip pop' },
  { name: 'country road' },
  { name: 'country' },
  { name: 'garage rock' },
  { name: 'folk rock' },
  { name: 'house' },
  { name: 'big room' },
  { name: 'latin hip hop' },
  { name: 'rap metal' },
  { name: 'rock en espanol' },
  { name: 'stomp and holler' },
  { name: 'funk rock' },
  { name: 'soul' },
  { name: 'dirty south rap' },
  { name: 'chamber pop' },
  { name: 'grupera' },
  { name: 'europop' },
  { name: 'underground hip hop' },
  { name: 'regional mexican' },
  { name: 'modern country rock' },
  { name: 'blues-rock' },
  { name: 'roots rock' },
  { name: 'synthpop' },
  { name: 'dance rock' },
  { name: 'alternative dance' },
  { name: 'new wave pop' },
  { name: 'neo soul' },
  { name: 'adult standards' },
  { name: 'emo' },
  { name: 'progressive house' },
  { name: 'west coast rap' },
  { name: 'new wave' },
  { name: 'classic funk rock' },
  { name: 'banda' },
  { name: 'quiet storm' },
  { name: 'latin alternative' },
  { name: 'neo-psychedelic' },
  { name: 'new rave' },
  { name: 'psychedelic rock' },
  { name: 'norteno' },
  { name: 'deep big room' },
  { name: 'spanish pop' },
  { name: 'progressive electro house' },
  { name: 'art rock' },
  { name: 'rap rock' },
  { name: 'trap latino' },
  { name: 'funk' },
  { name: 'teen pop' },
  { name: 'motown' },
  { name: 'shimmer pop' },
  { name: 'electronic' },
  { name: 'metal' },
  { name: 'deep pop r&b' },
  { name: 'deep indie r&b' },
  { name: 'brostep' },
  { name: 'deep tropical house' },
  { name: 'crunk' },
  { name: 'regional mexican pop' },
  { name: 'screamo' },
  { name: 'reggaeton flow' },
  { name: 'escape room' },
  { name: 'electronic trap' },
  { name: 'punk' },
  { name: 'new romantic' },
  { name: 'disco' },
  { name: 'pixie' },
  { name: 'swedish pop' },
  { name: 'acoustic pop' },
  { name: 'new americana' },
  { name: 'indie anthem-folk' },
  { name: 'pop reggaeton' },
  { name: 'metropopolis' },
  { name: 'metalcore' },
  { name: 'vapor soul' },
  { name: 'focus' },
  { name: 'hardcore hip hop' },
  { name: 'deep german hip hop' },
  { name: 'trap francais' },
  { name: 'jazz blues' },
  { name: 'brill building pop' },
  { name: 'deep funk carioca' },
  { name: 'folk' },
  { name: 'francoton' },
  { name: 'bass trap' },
  { name: 'swedish idol pop' },
  { name: 'southern rock' },
  { name: 'east coast hip hop' },
  { name: 'freak folk' },
  { name: 'chillwave' },
  { name: 'christian alternative rock' },
  { name: 'talent show' },
  { name: 'german hip hop' },
  { name: 'vocal jazz' },
  { name: 'groove metal' },
  { name: 'dance-punk' },
  { name: 'modern blues' },
  { name: 'ranchera' },
  { name: 'piano rock' },
  { name: 'worship' },
  { name: 'hollywood' },
  { name: 'soundtrack' },
  { name: 'boy band' },
  { name: 'g funk' },
  { name: 'lo-fi' },
  { name: 'british blues' },
  { name: 'redneck' },
  { name: 'soul blues' },
  { name: 'country rock' },
  { name: 'new jack swing' },
  { name: 'rock-and-roll' },
  { name: 'christian music' },
  { name: 'vegas indie' },
  { name: 'argentine rock' },
  { name: 'memphis soul' },
  { name: 'ccm' },
  { name: 'protopunk' },
  { name: 'noise pop' },
  { name: 'moombahton' },
  { name: 'deep underground hip hop' },
  { name: 'glam metal' },
  { name: 'deep pop edm' },
  { name: 'detroit hip hop' },
  { name: 'mpb' },
  { name: 'southern soul' },
  { name: 'sertanejo universitario' },
  { name: 'electric blues' },
  { name: 'cantautor' },
  { name: 'compositional ambient' },
  { name: 'german pop' },
  { name: 'traditional folk' },
  { name: 'melodic metalcore' },
  { name: 'britpop' },
  { name: 'outlaw country' },
  { name: 'christian rock' },
  { name: 'downtempo' },
  { name: 'deep dutch hip hop' },
  { name: 'underground pop rap' },
  { name: 'cumbia pop' },
  { name: 'dream pop' },
  { name: 'k-pop' },
  { name: 'complextro' },
  { name: 'alternative hip hop' },
  { name: 'korean pop' },
  { name: 'glam rock' },
  { name: 'chicago soul' },
  { name: 'tracestep' },
  { name: 'deep australian indie' },
  { name: 'funk metal' },
  { name: 'traditional country' },
  { name: 'grunge' },
  { name: 'pop emo' },
  { name: 'british invasion' },
  { name: 'deep german pop rock' },
  { name: 'indiecoustica' },
  { name: 'deep groove house' },
  { name: 'australian dance' },
  { name: 'trip hop' },
  { name: 'vapor twitch' },
  { name: 'grime' },
  { name: 'anthem worship' },
  { name: 'speed metal' },
  { name: 'scorecore' },
  { name: 'pagode' },
  { name: 'disco house' },
  { name: 'italian arena pop' },
  { name: 'italian pop' },
  { name: 'melancholia' },
  { name: 'classical' },
  { name: 'channel pop' },
  { name: 'indie psych-rock' },
  { name: 'catstep' },
  { name: 'lilith' },
  { name: 'anti-folk' },
  { name: 'samba' },
  { name: 'mariachi' },
  { name: 'reggae fusion' },
  { name: 'swedish folk pop' },
  { name: 'skate punk' },
  { name: 'minimal dub' },
  { name: 'slow core' },
  { name: 'roots reggae' },
  { name: 'video game music' },
  { name: 'cumbia' },
  { name: 'bubblegum pop' },
  { name: 'nu gaze' },
  { name: 'australian alternative rock' },
  { name: 'la indie' },
  { name: 'rockabilly' },
  { name: 'deep trap' },
  { name: 'duranguense' },
  { name: 'jazz' },
  { name: 'texas country' },
  { name: 'german techno' },
  { name: 'symphonic rock' },
  { name: 'chillhop' },
  { name: 'dancehall' },
  { name: 'bachata' },
  { name: 'progressive metal' },
  { name: 'alt-indie rock' },
  { name: 'bossa nova' },
  { name: 'reggae' },
  { name: 'candy pop' },
  { name: 'otacore' },
  { name: 'lift kit' },
  { name: 'french pop' },
  { name: 'nu jazz' },
  { name: 'madchester' },
  { name: 'merseybeat' },
  { name: 'romantic' },
  { name: 'comic' },
  { name: 'deep latin hip hop' },
  { name: 'progressive rock' },
  { name: 'space rock' },
  { name: 'power metal' },
  { name: 'classify' },
  { name: 'deep danish pop' },
  { name: 'alternative country' },
  { name: 'danish pop' },
  { name: 'etherpop' },
  { name: 'hoerspiel' },
  { name: 'uk funky' },
  { name: 'thrash metal' },
  { name: 'spanish rock' },
  { name: 'sky room' },
  { name: 'sertanejo' },
  { name: 'jam band' },
  { name: 'eurodance' },
  { name: 'trance' },
  { name: 'deep cumbia sonidera' },
  { name: 'nashville sound' },
  { name: 'mandopop' },
  { name: 'swedish indie rock' },
  { name: 'finnish dance pop' },
  { name: 'lounge' },
  { name: 'taiwanese pop' },
  { name: 'deep southern trap' },
  { name: 'brazilian hip hop' },
  { name: 'industrial metal' },
  { name: 'french hip hop' },
  { name: 'chamber psych' },
  { name: 'jazz funk' },
  { name: 'bolero' },
  { name: 'deep euro house' },
  { name: 'bow pop' },
  { name: 'swedish alternative rock' },
  { name: 'post-punk' },
  { name: 'deep taiwanese pop' },
  { name: 'shiver pop' },
  { name: 'turkish pop' },
  { name: 'alternative emo' },
  { name: 'progressive trance' },
  { name: 'cool jazz' },
  { name: 'bubblegum dance' },
  { name: 'forro' },
  { name: 'finnish pop' },
  { name: 'salsa' },
  { name: 'c-pop' },
  { name: 'show tunes' },
  { name: 'world worship' },
  { name: 'filter house' },
  { name: 'nueva cancion' },
  { name: 'preverb' },
  { name: 'country dawn' },
  { name: 'punk blues' },
  { name: 'brooklyn indie' },
  { name: 'post-screamo' },
  { name: 'cabaret' },
  { name: 'merengue' },
  { name: 'power pop' },
  { name: 'minimal' },
  { name: 'opm' },
  { name: 'swedish eurodance' },
  { name: 'uk post-punk' },
  { name: 'vocal house' },
  { name: 'danspunk' },
  { name: 'indie garage rock' },
  { name: 'deep new americana' },
  { name: 'axe' },
  { name: 'chanson' },
  { name: 'melodic death metal' },
  { name: 'industrial rock' },
  { name: 'jazz fusion' },
  { name: 'deep regional mexican' },
  { name: 'italian hip hop' },
  { name: 'modern classical' },
  { name: 'garage psych' },
  { name: 'classic swedish pop' },
  { name: 'turkish rock' },
  { name: 'bebop' },
  { name: 'post rock' },
  { name: 'spanish pop rock' },
  { name: 'deep swedish hip hop' },
  { name: 'irish rock' },
  { name: 'dutch pop' },
  { name: 'movie tunes' },
  { name: 'post-disco' },
  { name: 'contemporary post-bop' },
  { name: 'west coast trap' },
  { name: 'swedish hip hop' },
  { name: 'ninja' },
  { name: 'texas blues' },
  { name: 'cantopop' },
  { name: 'blues' },
  { name: 'dutch house' },
  { name: 'anthem emo' },
  { name: 'norwegian pop' },
  { name: 'chillstep' },
  { name: 'minimal techno' },
  { name: 'chilean rock' },
  { name: 'canadian indie' },
  { name: 'experimental rock' },
  { name: 'dutch hip hop' },
  { name: 'acid jazz' },
  { name: 'wrestling' },
  { name: 'melodic hardcore' },
  { name: 'easy listening' },
  { name: 'fourth world' },
  { name: 'progressive bluegrass' },
  { name: 'microhouse' },
  { name: 'big beat' },
  { name: 'norwegian indie' },
  { name: 'hip house' },
  { name: 'post-hardcore' },
  { name: 'vallenato' },
  { name: 'rock gaucho' },
  { name: 'broadway' },
  { name: 'tech house' },
  { name: 'indonesian pop' },
  { name: 'traditional blues' },
  { name: 'electro latino' },
  { name: 'dreamo' },
  { name: 'noise rock' },
  { name: 'aussietronica' },
  { name: 'french rock' },
  { name: 'soul jazz' },
  { name: 'antiviral pop' },
  { name: 'sheffield indie' },
  { name: 'australian pop' },
  { name: 'country blues' },
  { name: 'french indie pop' },
  { name: 'swedish indie pop' },
  { name: 'uplifting trance' },
  { name: 'uk garage' },
  { name: 'latin christian' },
  { name: 'french indietronica' },
  { name: 'hard bop' },
  { name: 'swing' },
  { name: 'country gospel' },
  { name: 'ambient' },
  { name: 'azontobeats' },
  { name: 'russelater' },
  { name: 'reggae rock' },
  { name: 'lovers rock' },
  { name: 'electro swing' },
  { name: 'mexican indie' },
  { name: 'epicore' },
  { name: 'french reggae' },
  { name: 'neo classical metal' },
  { name: 'new age' },
  { name: 'zapstep' },
  { name: 'celtic rock' },
  { name: 'turntablism' },
  { name: 'death metal' },
  { name: 'latin jazz' },
  { name: 'industrial' },
  { name: 'stoner rock' },
  { name: 'nu disco' },
  { name: 'indie rockism' },
  { name: 'latin metal' },
  { name: 'ska' },
  { name: 'classic norwegian pop' },
  { name: 'deep melodic euro house' },
  { name: 'indie punk' },
  { name: 'gauze pop' },
  { name: 'deep funk' },
  { name: 'swedish synthpop' },
  { name: 'hyphy' },
  { name: 'gothic metal' },
  { name: 'progressive post-hardcore' },
  { name: 'merengue urbano' },
  { name: 'electro' },
  { name: 'german metal' },
  { name: 'deep chiptune' },
  { name: 'drum and bass' },
  { name: 'flamenco' },
  { name: 'death core' },
  { name: 'german pop rock' },
  { name: 'suomi rock' },
  { name: 'pinoy alternative' },
  { name: 'canadian metal' },
  { name: 'memphis blues' },
  { name: 'ska punk' },
  { name: 'brazilian gospel' },
  { name: 'anime' },
  { name: 'chicago blues' },
  { name: 'drill' },
  { name: 'christian uplift' },
  { name: 'cumbia villera' },
  { name: 'christian hip hop' },
  { name: 'experimental' },
  { name: 'stomp pop' },
  { name: 'turkish jazz' },
  { name: 'stride' },
  { name: 'world' },
  { name: 'deep ccm' },
  { name: 'dub' },
  { name: 'smooth jazz' },
  { name: 'j-pop' },
  { name: 'trova' },
  { name: 'old school hip hop' },
  { name: 'neue deutsche harte' },
  { name: 'hardcore punk' },
  { name: 'pub rock' },
  { name: 'louvor' },
  { name: 'afrobeats' },
  { name: 'indie jazz' },
  { name: 'new orleans blues' },
  { name: 'spanish indie pop' },
  { name: 'big band' },
  { name: 'comedy' },
  { name: 'mambo' },
  { name: 'baroque' },
  { name: 'icelandic pop' },
  { name: 'acoustic blues' },
  { name: 'pop house' },
  { name: 'electroclash' },
  { name: 'deep texas country' },
  { name: 'delta blues' },
  { name: 'shoegaze' },
  { name: 'deep disco house' },
  { name: 'new weird america' },
  { name: 'deep swedish indie pop' },
  { name: 'djent' },
  { name: 'cowboy western' },
  { name: 'cumbia sonidera' },
  { name: 'turkish folk' },
  { name: 'gospel' },
  { name: 'finnish hip hop' },
  { name: 'classical period' },
  { name: 'symphonic metal' },
  { name: 'swedish metal' },
  { name: 'wonky' },
  { name: 'norwegian rock' },
  { name: 'minimal tech house' },
  { name: 'melbourne bounce' },
  { name: 'indonesian indie' },
  { name: 'vaporwave' },
  { name: 'groove room' },
  { name: 'relaxative' },
  { name: 'stoner metal' },
  { name: 'tejano' },
  { name: 'nwobhm' },
  { name: 'piedmont blues' },
  { name: 'sleep' },
  { name: 'j-rock' },
  { name: 'dansband' },
  { name: 'desi' },
  { name: 'filthstep' },
  { name: 'drone' },
  { name: 'bass music' },
  { name: 'liquid funk' },
  { name: 'argentine reggae' },
  { name: 'gothic symphonic metal' },
  { name: 'doo-wop' },
  { name: 'celtic' },
  { name: 'christian relaxative' },
  { name: 'hardstyle' },
  { name: 'alternative r&b' },
  { name: 'spanish punk' },
  { name: 'indian pop' },
  { name: 'meditation' },
  { name: 'boogaloo' },
  { name: 'memphis hip hop' },
  { name: 'afrobeat' },
  { name: 'chicano rap' },
  { name: 'cubaton' },
  { name: 'operatic pop' },
  { name: 'dangdut' },
  { name: 'louisiana blues' },
  { name: 'viking metal' },
  { name: 'polish pop' },
  { name: 'schlager' },
  { name: 'contemporary jazz' },
  { name: 'future garage' },
  { name: 'british folk' },
  { name: 'danish pop rock' },
  { name: 'deep hardstyle' },
  { name: 'desi hip hop' },
  { name: 'hands up' },
  { name: 'spanish hip hop' },
  { name: 'crossover thrash' },
  { name: 'underground rap' },
  { name: 'k-hop' },
  { name: 'healing' },
  { name: 'intelligent dance music' },
  { name: 'classic danish pop' },
  { name: 'a cappella' },
  { name: 'boston rock' },
  { name: 'german indie' },
  { name: 'environmental' },
  { name: 'children’s music' },
  { name: 'rumba' },
  { name: 'deep house' },
  { name: 'norwegian hip hop' },
  { name: 'glitch hop' },
  { name: 'arabesk' },
  { name: 'velha guarda' },
  { name: 'vapor pop' },
  { name: 'mathcore' },
  { name: 'jangle pop' },
  { name: 'opera' },
  { name: 'levenslied' },
  { name: 'australian hip hop' },
  { name: 'folk punk' },
  { name: 'northern soul' },
  { name: 'azonto' },
  { name: 'electropowerpop' },
  { name: 'sludge metal' },
  { name: 'alternative pop rock' },
  { name: 'abstract hip hop' },
  { name: 'brazilian indie' },
  { name: 'swamp blues' },
  { name: 'nu-cumbia' },
  { name: 'retro electro' },
  { name: 'zolo' },
  { name: 'jump blues' },
  { name: 'spanish new wave' },
  { name: 'filmi' },
  { name: 'coverchill' },
  { name: 'jazz metal' },
  { name: 'liedermacher' },
  { name: 'piano blues' },
  { name: 'danseband' },
  { name: 'neoclassical' },
  { name: 'sleaze rock' },
  { name: 'fingerstyle' },
  { name: 'eurovision' },
  { name: 'breakbeat' },
  { name: 'deep turkish pop' },
  { name: 'j-dance' },
  { name: 'alternative ccm' },
  { name: 'polynesian pop' },
  { name: 'german punk' },
  { name: 'riddim' },
  { name: 'finnish metal' },
  { name: 'brazilian punk' },
  { name: 'welsh rock' },
  { name: 'australian country' },
  { name: 'glitch' },
  { name: 'japanese r&b' },
  { name: 'future funk' },
  { name: 'j-rap' },
  { name: 'reading' },
  { name: 'italian indie pop' },
  { name: 'rock steady' },
  { name: 'portland indie' },
  { name: 'folk metal' },
  { name: 'bluegrass' },
  { name: 'fluxwork' },
  { name: 'technical death metal' },
  { name: 'dutch rock' },
  { name: 'uk drill' },
  { name: 'canadian country' },
  { name: 'christian metal' },
  { name: 'grave wave' },
  { name: 'stomp and flutter' },
  { name: 'hardcore techno' },
  { name: 'neo-singer-songwriter' },
  { name: 'discofox' },
  { name: 'float house' },
  { name: 'russian pop' },
  { name: 'electro jazz' },
  { name: 'kiwi rock' },
  { name: 'alternative pop' },
  { name: 'deep uplifting trance' },
  { name: 'slow game' },
  { name: 'no wave' },
  { name: 'turkish hip hop' },
  { name: 'hard alternative' },
  { name: 'scottish rock' },
  { name: 'doom metal' },
  { name: 'black metal' },
  { name: 'folklore argentino' },
  { name: 'progressive uplifting trance' },
  { name: 'deep norteno' },
  { name: 'cuban rumba' },
  { name: 'j-metal' },
  { name: 'neurofunk' },
  { name: 'post-metal' },
  { name: 'dark jazz' },
  { name: 'polish hip hop' },
  { name: 'chicago indie' },
  { name: 'strut' },
  { name: 'modern performance' },
  { name: 'ectofolk' },
  { name: 'jungle' },
  { name: 'classic italian pop' },
  { name: 'nasheed' },
  { name: 'pop flamenco' },
  { name: 'belgian rock' },
  { name: 'austindie' },
  { name: 'peruvian rock' },
  { name: 'italo dance' },
  { name: 'deathgrind' },
  { name: 'jump up' },
  { name: 'techno' },
  { name: 'symphonic black metal' },
  { name: 'pagan black metal' },
  { name: 'british alternative rock' },
  { name: 'kirtan' },
  { name: 'orgcore' },
  { name: 'malaysian pop' },
  { name: 'christian dance' },
  { name: 'idol' },
  { name: 'irish folk' },
  { name: 'new tribe' },
  { name: 'brega' },
  { name: 'western swing' },
  { name: 'post-doom metal' },
  { name: 'drift' },
  { name: 'medieval rock' },
  { name: 'bay area indie' },
  { name: 'dark wave' },
  { name: 'carnaval' },
  { name: 'happy hardcore' },
  { name: 'rap chileno' },
  { name: 'puerto rican rock' },
  { name: 'portuguese rock' },
  { name: 'dubstep' },
  { name: 'new orleans jazz' },
  { name: 'soca' },
  { name: 'russian rock' },
  { name: 'classic finnish pop' },
  { name: 'seattle indie' },
  { name: 'electrofox' },
  { name: 'chamame' },
  { name: 'spanish noise pop' },
  { name: 'ambeat' },
  { name: 'albuquerque indie' },
  { name: 'austropop' },
  { name: 'italian disco' },
  { name: 'arab pop' },
  { name: 'italian pop rock' },
  { name: 'hardcore' },
  { name: 'gbvfi' },
  { name: 'soul flow' },
  { name: 'harmonica blues' },
  { name: 'math pop' },
  { name: 'baile funk' },
  { name: 'brutal death metal' },
  { name: 'progressive deathcore' },
  { name: 'medieval' },
  { name: 'salsa international' },
  { name: 'melodipop' },
  { name: 'celtic punk' },
  { name: 'british indie rock' },
  { name: 'quebecois' },
  { name: 'grindcore' },
  { name: 'psychedelic trance' },
  { name: 'ethereal wave' },
  { name: 'outsider house' },
  { name: 'chicago house' },
  { name: 'math rock' },
  { name: 'garage pop' },
  { name: 'romantico' },
  { name: 'e6fi' },
  { name: 'ebm' },
  { name: 'rock catala' },
  { name: 'psychedelic doom' },
  { name: 'freestyle' },
  { name: 'mexican rock-and-roll' },
  { name: 'balearic' },
  { name: 'colombian rock' },
  { name: 'laiko' },
  { name: 'nintendocore' },
  { name: 'twee pop' },
  { name: 'japanese city pop' },
  { name: 'deep minimal techno' },
  { name: 'barnmusik' },
  { name: 'classic russian rock' },
  { name: 'classic finnish rock' },
  { name: 'indie dream pop' },
  { name: 'bmore' },
  { name: 'ska revival' },
  { name: 'avantgarde metal' },
  { name: 'entehno' },
  { name: 'african gospel' },
  { name: 'avant-garde jazz' },
  { name: 'mande pop' },
  { name: 'world fusion' },
  { name: 'nordic house' },
  { name: 'nu age' },
  { name: 'brazilian ccm' },
  { name: 'drill and bass' },
  { name: 'warm drone' },
  { name: 'polish punk' },
  { name: 'straight edge' },
  { name: 'free jazz' },
  { name: 'swedish hard rock' },
  { name: 'deep comedy' },
  { name: 'acid house' },
  { name: 'post-post-hardcore' },
  { name: 'ye ye' },
  { name: 'electro-industrial' },
  { name: 'turbo folk' },
  { name: 'chaotic hardcore' },
  { name: 'funky tech house' },
  { name: 'mashup' },
  { name: 'speed garage' },
  { name: 'destroy techno' },
  { name: 'gothic rock' },
  { name: 'canterbury scene' },
  { name: 'sertanejo tradicional' },
  { name: 'dansktop' },
  { name: 'bassline' },
  { name: 'oi' },
  { name: 'j-idol' },
  { name: 'nursery' },
  { name: 'deep latin christian' },
  { name: 'african rock' },
  { name: 'gypsy jazz' },
  { name: 'k-indie' },
  { name: 'christian hardcore' },
  { name: 'singaporean pop' },
  { name: 'romanian pop' },
  { name: 'retro metal' },
  { name: 'emo punk' },
  { name: 'classic garage rock' },
  { name: 'surf music' },
  { name: 'kindermusik' },
  { name: 'classic chinese pop' },
  { name: 'substep' },
  { name: 'kraut rock' },
  { name: 'world meditation' },
  { name: 'argentine indie' },
  { name: 'futurepop' },
  { name: 'laboratorio' },
  { name: 'tango' },
  { name: 'classical performance' },
  { name: 'vancouver indie' },
  { name: 'mandible' },
  { name: 'russiavision' },
  { name: 'slovak pop' },
  { name: 'steampunk' },
  { name: 'fado' },
  { name: 'old-time' },
  { name: 'chill lounge' },
  { name: 'bhangra' },
  { name: 'volksmusik' },
  { name: 'freakbeat' },
  { name: 'christian punk' },
  { name: 'norwegian metal' },
  { name: 'hawaiian' },
  { name: 'cello' },
  { name: 'dixieland' },
  { name: 'psychobilly' },
  { name: 'canzone napoletana' },
  { name: 'punjabi' },
  { name: 'danish hip hop' },
  { name: 'horror punk' },
  { name: 'alternative roots rock' },
  { name: 'orchestral' },
  { name: 'atmospheric black metal' },
  { name: 'musica para ninos' },
  { name: 'zouk riddim' },
  { name: 'uk hip hop' },
  { name: 'comedy rock' },
  { name: 'athens indie' },
  { name: 'gabba' },
  { name: 'latin electronica' },
  { name: 'early music' },
  { name: 'turkish alternative' },
  { name: 'drone metal' },
  { name: 'kabarett' },
  { name: 'deep talent show' },
  { name: 'classical piano' },
  { name: 'j-poprock' },
  { name: 'swedish reggae' },
  { name: 'choro' },
  { name: 'psychill' },
  { name: 'columbus ohio indie' },
  { name: 'progressive psytrance' },
  { name: 'venezuelan rock' },
  { name: 'persian pop' },
  { name: 'italian metal' },
  { name: 'theme' },
  { name: 'detroit techno' },
  { name: 'neo-trad metal' },
  { name: 'jazz trio' },
  { name: 'russian hip hop' },
  { name: 'deep latin alternative' },
  { name: 'p funk' },
  { name: 'czech rock' },
  { name: 'abstract beats' },
  { name: 'hungarian rock' },
  { name: 'israeli rock' },
  { name: 'ballroom' },
  { name: 'swedish jazz' },
  { name: 'aggrotech' },
  { name: 'electro bailando' },
  { name: 'deep indian pop' },
  { name: 'praise' },
  { name: 'kizomba' },
  { name: 'power-pop punk' },
  { name: 'bubble trance' },
  { name: 'ok indie' },
  { name: 'progressive trance house' },
  { name: 'neo-progressive' },
  { name: 'avant-garde' },
  { name: 'vintage italian soundtrack' },
  { name: 'hungarian pop' },
  { name: 'swedish punk' },
  { name: 'dub techno' },
  { name: 'black thrash' },
  { name: 'choral' },
  { name: 'voidgaze' },
  { name: 'tribal house' },
  { name: 'popgaze' },
  { name: 'indie psych-pop' },
  { name: 'visual kei' },
  { name: 'anime score' },
  { name: 'melodic hard rock' },
  { name: 'power blues-rock' },
  { name: 'andean' },
  { name: 'dark cabaret' },
  { name: 'shimmer psych' },
  { name: 'french movie tunes' },
  { name: 'goregrind' },
  { name: 'deep pop punk' },
  { name: 'exotica' },
  { name: 'classic colombian pop' },
  { name: 'barnemusikk' },
  { name: 'basque rock' },
  { name: 'mizrahi' },
  { name: 'rai' },
  { name: 'czech folk' },
  { name: 'folkmusik' },
  { name: 'classic turkish pop' },
  { name: 'horrorcore' },
  { name: 'perth indie' },
  { name: 'deep chill' },
  { name: 'renaissance' },
  { name: 'j-indie' },
  { name: 'fidget house' },
  { name: 'deep melodic metalcore' },
  { name: 'violin' },
  { name: 'nu skool breaks' },
  { name: 'christelijk' },
  { name: 'highlife' },
  { name: 'string quartet' },
  { name: 'timba' },
  { name: 'chiptune' },
  { name: 'belly dance' },
  { name: 'zouk' },
  { name: 'vintage swedish pop' },
  { name: 'brass band' },
  { name: 'russian punk' },
  { name: 'kids dance party' },
  { name: 'classic peruvian pop' },
  { name: 'acid techno' },
  { name: 'southern gospel' },
  { name: 'sega' },
  { name: 'lds' },
  { name: 'vienna indie' },
  { name: 'turkish classical' },
  { name: 'mod revival' },
  { name: 'neue deutsche welle' },
  { name: 'deep liquid' },
  { name: 'spanish reggae' },
  { name: 'norwegian gospel' },
  { name: 'digital hardcore' },
  { name: 'deep soul house' },
  { name: 'albanian pop' },
  { name: 'c86' },
  { name: 'french folk pop' },
  { name: 'bouncy house' },
  { name: 'girl group' },
  { name: 'classic icelandic pop' },
  { name: 'polish reggae' },
  { name: 'thai idol' },
  { name: 'swiss rock' },
  { name: 'hip hop tuga' },
  { name: 'college a cappella' },
  { name: 'instrumental post rock' },
  { name: 'irish country' },
  { name: 'dominican pop' },
  { name: 'native american' },
  { name: 'uk dub' },
  { name: 'southern soul blues' },
  { name: 'bounce' },
  { name: 'jazz bass' },
  { name: 'rio de la plata' },
  { name: 'hauntology' },
  { name: 'catalan folk' },
  { name: 'nordic folk' },
  { name: 'miami bass' },
  { name: 'arab folk' },
  { name: 'yugoslav rock' },
  { name: 'ambient idm' },
  { name: 'swamp pop' },
  { name: 'classic belgian pop' },
  { name: 'beats' },
  { name: 'classic polish pop' },
  { name: 'spanish folk' },
  { name: 'vintage french electronic' },
  { name: 'riot grrrl' },
  { name: 'free improvisation' },
  { name: 'hip hop quebecois' },
  { name: 'shibuya-kei' },
  { name: 'garage punk' },
  { name: 'pakistani pop' },
  { name: 'harpsichord' },
  { name: 'tin pan alley' },
  { name: 'musica nativista' },
  { name: 'classical guitar' },
  { name: 'appalachian folk' },
  { name: 'deep christian rock' },
  { name: 'morna' },
  { name: 'thai pop' },
  { name: 'desert blues' },
  { name: 'cante flamenco' },
  { name: 'new age piano' },
  { name: 'samba-enredo' },
  { name: 'polish indie' },
  { name: 'vintage tango' },
  { name: 'balkan brass' },
  { name: 'thrash core' },
  { name: 'italian jazz' },
  { name: 'atmospheric post rock' },
  { name: 'estonian pop' },
  { name: 'chanson quebecois' },
  { name: 'croatian pop' },
  { name: 'soukous' },
  { name: 'qawwali' },
  { name: 'boogie-woogie' },
  { name: 'brazilian composition' },
  { name: 'czech hip hop' },
  { name: 'modern uplift' },
  { name: 'serialism' },
  { name: 'disco polo' },
  { name: 'stomp and whittle' },
  { name: 'neo-rockabilly' },
  { name: 'hiplife' },
  { name: 'workout' },
  { name: 'deep tech house' },
  { name: 'karneval' },
  { name: 'underground latin hip hop' },
  { name: 'kompa' },
  { name: 'electropunk' },
  { name: 'melodic power metal' },
  { name: 'drumfunk' },
  { name: 'metal guitar' },
  { name: 'portuguese pop' },
  { name: 'tico' },
  { name: 'finnish indie' },
  { name: 'ecuadoria' },
  { name: 'electronica' },
  { name: 'cyber metal' },
  { name: 'german oi' },
  { name: 'full on' },
  { name: 'kwaito house' },
  { name: 'vietnamese pop' },
  { name: 'vocaloid' },
  { name: 'heavy alternative' },
  { name: 'outsider' },
  { name: 'deep flow' },
  { name: 'irish indie' },
  { name: 'gothic alternative' },
  { name: 'jumpstyle' },
  { name: 'k-rock' },
  { name: 'crust punk' },
  { name: 'psych gaze' },
  { name: 'fake' },
  { name: 'german show tunes' },
  { name: 'brutal deathcore' },
  { name: 'orquesta tropical' },
  { name: 'ethiopian pop' },
  { name: 'blackgaze' },
  { name: 'calypso' },
  { name: 'slovak hip hop' },
  { name: 'mbalax' },
  { name: 'grunge pop' },
  { name: 'beatdown' },
  { name: 'rosary' },
  { name: 'composition d' },
  { name: 'latvian pop' },
  { name: 'j-ambient' },
  { name: 'traditional rock ‘n roll' },
  { name: 'rva indie' },
  { name: 'dark black metal' },
  { name: 'alternative americana' },
  { name: 'deep acoustic pop' },
  { name: 'classic venezuelan pop' },
  { name: 'witch house' },
  { name: 'orquesta tipica' },
  { name: 'austrian hip hop' },
  { name: 'concert piano' },
  { name: 'electro dub' },
  { name: 'ragtime' },
  { name: 'louisville indie' },
  { name: 'drone folk' },
  { name: 'canadian hip hop' },
  { name: 'lounge house' },
  { name: 'hungarian hip hop' },
  { name: 'ukrainian rock' },
  { name: 'neofolk' },
  { name: 'world chill' },
  { name: 'traditional ska' },
  { name: 'denver indie' },
  { name: 'deep smooth jazz' },
  { name: 'anarcho-punk' },
  { name: 'oshare kei' },
  { name: 'yoik' },
  { name: 'leeds indie' },
  { name: 'geek rock' },
  { name: 'indie emo' },
  { name: 'funk carioca' },
  { name: 'abstract' },
  { name: 'traditional british folk' },
  { name: 'dirty texas rap' },
  { name: 'judaica' },
  { name: 'japanese psychedelic' },
  { name: 'classic czech pop' },
  { name: 'deep dance pop' },
  { name: 'broken beat' },
  { name: 'deep rai' },
  { name: 'lithumania' },
  { name: 'hard minimal techno' },
  { name: 'lo star' },
  { name: 'modern southern rock' },
  { name: 'neo-synthpop' },
  { name: 'nwothm' },
  { name: 'zouglou' },
  { name: 'makossa' },
  { name: 'footwork' },
  { name: 'zillertal' },
  { name: 'acousmatic' },
  { name: 'mexican son' },
  { name: 'ukulele' },
  { name: 'deep gothic post-punk' },
  { name: 'deep soundtrack' },
  { name: 'swiss hip hop' },
  { name: 'deep neofolk' },
  { name: 'tone' },
  { name: 'ghazal' },
  { name: 'deep contemporary country' },
  { name: 'psychedelic blues-rock' },
  { name: 'musiikkia lapsille' },
  { name: 'semba' },
  { name: 'deep adult standards' },
  { name: 'islamic recitation' },
  { name: 'blaskapelle' },
  { name: 'guidance' },
  { name: 'kurdish folk' },
  { name: 'tribute' },
  { name: 'atmospheric post-metal' },
  { name: 'darkstep' },
  { name: 'vegan straight edge' },
  { name: 'nerdcore' },
  { name: 'new beat' },
  { name: 'crack rock steady' },
  { name: 'swedish prog' },
  { name: 'danish indie' },
  { name: 'belgian indie' },
  { name: 'slavic metal' },
  { name: 'classic soundtrack' },
  { name: 'slc indie' },
  { name: 'classic french pop' },
  { name: 'kayokyoku' },
  { name: 'electro trash' },
  { name: 'traditional swing' },
  { name: 'garage punk blues' },
  { name: 'deep german punk' },
  { name: 'deep discofox' },
  { name: 'indian classical' },
  { name: 'classic afrobeat' },
  { name: 'black death' },
  { name: 'dark hardcore' },
  { name: 'minimal wave' },
  { name: 'zydeco' },
  { name: 'downtempo fusion' },
  { name: 'jazz brass' },
  { name: 'australian indie' },
  { name: 'underground power pop' },
  { name: 'gothic americana' },
  { name: 'traditional scottish folk' },
  { name: 'classic dutch pop' },
  { name: 'nl folk' },
  { name: 'didgeridoo' },
  { name: 'schranz' },
  { name: 'funky breaks' },
  { name: 'motivation' },
  { name: 'indie singer-songwriter' },
  { name: 'spanish invasion' },
  { name: 'euroska' },
  { name: 'ragga jungle' },
  { name: 'breakcore' },
  { name: 'library music' },
  { name: 'deep psychobilly' },
  { name: 'michigan indie' },
  { name: 'chalga' },
  { name: 'electronicore' },
  { name: 'corrosion' },
  { name: 'south african jazz' },
  { name: 'usbm' },
  { name: 'solipsynthm' },
  { name: 'progressive alternative' },
  { name: 'neurostep' },
  { name: 'deep brazilian pop' },
  { name: 'deep orchestral' },
  { name: 'deep melodic hard rock' },
  { name: 'string folk' },
  { name: 'dark ambient' },
  { name: 'mallet' },
  { name: 'deep disco' },
  { name: 'power violence' },
  { name: 'contemporary composition' },
  { name: 'fast melodic punk' },
  { name: 'finnish hardcore' },
  { name: 'martial industrial' },
  { name: 'classic russian pop' },
  { name: 'hindustani classical' },
  { name: 'enka' },
  { name: 'russian alternative' },
  { name: 'minimal melodic techno' },
  { name: 'beach music' },
  { name: 'japanese jazztronica' },
  { name: 'neo metal' },
  { name: 'rebetiko' },
  { name: 'future ambient' },
  { name: 'tzadik' },
  { name: 'kwaito' },
  { name: 'liturgical' },
  { name: 'abstract idm' },
  { name: 'ostrock' },
  { name: 'gospel reggae' },
  { name: 'faroese pop' },
  { name: 'musica per bambini' },
  { name: 'melodic progressive metal' },
  { name: 'monastic' },
  { name: 'scratch' },
  { name: 'ambient psychill' },
  { name: 'string band' },
  { name: 'french punk' },
  { name: 'panpipe' },
  { name: 'afrikaans' },
  { name: 'japanoise' },
  { name: 'power electronics' },
  { name: 'byzantine' },
  { name: 'russian folk' },
  { name: 'gamecore' },
  { name: 'rap metalcore' },
  { name: 'traditional soul' },
  { name: 'coupe decale' },
  { name: 'musique pour enfants' },
  { name: 'consort' },
  { name: 'bass trip' },
  { name: 'porro' },
  { name: 'norwegian jazz' },
  { name: 'italian progressive rock' },
  { name: 'galego' },
  { name: 'hard house' },
  { name: 'bossa nova jazz' },
  { name: 'spanish classical' },
  { name: 'classic schlager' },
  { name: 'nz indie' },
  { name: 'slam death metal' },
  { name: 'bemani' },
  { name: 'manele' },
  { name: 'deep opera' },
  { name: 'deep progressive trance' },
  { name: 'deep liquid bass' },
  { name: 'magyar' },
  { name: 'german ccm' },
  { name: 'deep ambient' },
  { name: 'polyphony' },
  { name: 'deep soft rock' },
  { name: 'iskelma' },
  { name: 'bay area hip hop' },
  { name: 'wind ensemble' },
  { name: 'shanty' },
  { name: 'military band' },
  { name: 'romanian rock' },
  { name: 'luk thung' },
  { name: 'greek indie' },
  { name: 'funeral doom' },
  { name: 'flick hop' },
  { name: 'chaotic black metal' },
  { name: 'deep folk metal' },
  { name: 'armenian folk' },
  { name: 'skinhead reggae' },
  { name: 'tekno' },
  { name: 'italian folk' },
  { name: 'screamocore' },
  { name: 'marching band' },
  { name: 'indie fuzzpop' },
  { name: 'persian traditional' },
  { name: 'neo-pagan' },
  { name: 'dark psytrance' },
  { name: 'african percussion' },
  { name: 'go-go' },
  { name: 'spoken word' },
  { name: 'breton folk' },
  { name: 'vapor house' },
  { name: 'depressive black metal' },
  { name: 'minimal dubstep' },
  { name: 'jig and reel' },
  { name: 'deep canadian indie' },
  { name: 'experimental psych' },
  { name: 'deep sunset lounge' },
  { name: 'indie shoegaze' },
  { name: 'vintage chanson' },
  { name: 'harp' },
  { name: 'swedish pop punk' },
  { name: 'indorock' },
  { name: 'punta' },
  { name: 'kuduro' },
  { name: 'thrash-groove metal' },
  { name: 'doujin' },
  { name: 'cornetas y tambores' },
  { name: 'accordion' },
  { name: 'pipe band' },
  { name: 'ghettotech' },
  { name: 'corsican folk' },
  { name: 'speedcore' },
  { name: 'outer hip hop' },
  { name: 'jazz orchestra' },
  { name: 'danish jazz' },
  { name: 'trash rock' },
  { name: 'indie pop rock' },
  { name: 'jug band' },
  { name: 'remix' },
  { name: 'benga' },
  { name: 'neo-industrial rock' },
  { name: 'west african jazz' },
  { name: 'nepali' },
  { name: 'hebrew pop' },
  { name: 'bulgarian rock' },
  { name: 'geek folk' },
  { name: 'deep darkpsy' },
  { name: 'deep happy hardcore' },
  { name: 'blues-rock guitar' },
  { name: 'klezmer' },
  { name: 'triangle indie' },
  { name: 'black sludge' },
  { name: 'deep german indie' },
  { name: 'barbershop' },
  { name: 'greek hip hop' },
  { name: 'brass ensemble' },
  { name: 'j-core' },
  { name: 'dark minimal techno' },
  { name: 'screamo punk' },
  { name: 'cumbia funk' },
  { name: 'greek house' },
  { name: 'zim' },
  { name: 'technical brutal death metal' },
  { name: 'ambient fusion' },
  { name: 'deep jazz guitar' },
  { name: 'italian punk' },
  { name: 'british dance band' },
  { name: 'hard glam' },
  { name: 'chinese traditional' },
  { name: 'commons' },
  { name: 'dallas indie' },
  { name: 'light music' },
  { name: 'deep deep house' },
  { name: 'northern irish indie' },
  { name: 'sinhala' },
  { name: 'j-reggae' },
  { name: 'gospel blues' },
  { name: 'power noise' },
  { name: 'abstractro' },
  { name: 'throat singing' },
  { name: 'street punk' },
  { name: 'capoeira' },
  { name: 'post-disco soul' },
  { name: 'drama' },
  { name: 'deep vocal house' },
  { name: 'deep vocal jazz' },
  { name: 'vintage jazz' },
  { name: 'deep melodic death metal' },
  { name: 'deep indie singer-songwriter' },
  { name: 'mantra' },
  { name: 'british brass band' },
  { name: 'contemporary folk' },
  { name: 'chinese indie rock' },
  { name: 'finnish jazz' },
  { name: 'deep psytrance' },
  { name: 'soda pop' },
  { name: 'unblack metal' },
  { name: 'traditional funk' },
  { name: 'fussball' },
  { name: 'deep ragga' },
  { name: 'deep new wave' },
  { name: 'covertrance' },
  { name: 'deep full on' },
  { name: 'deep southern soul' },
  { name: 'steelpan' },
  { name: 'cajun' },
  { name: 'stl indie' },
  { name: 'japanese traditional' },
  { name: 'poetry' },
  { name: 'dubsteppe' },
  { name: 'carnatic' },
  { name: 'makina' },
  { name: 'deep indie pop' },
  { name: 'classic eurovision' },
  { name: 'noise punk' },
  { name: 'slash punk' },
  { name: 'spanish indie rock' },
  { name: 'c64' },
  { name: 'college marching band' },
  { name: 'muziek voor kinderen' },
  { name: 'grisly death metal' },
  { name: 'gothic post-punk' },
  { name: 'musique concrete' },
  { name: 'chamber choir' },
  { name: 'oratory' },
  { name: 'hardcore breaks' },
  { name: 'deep east coast hip hop' },
  { name: 'deep funk house' },
  { name: 'mexican traditional' },
  { name: 'classical organ' },
  { name: 'classical flute' },
  { name: 'fallen angel' },
  { name: 'skiffle' },
  { name: 'sunset lounge' },
  { name: 'organic ambient' },
  { name: 'bangla' },
  { name: 'belorush' },
  { name: 'deep indie rock' },
  { name: 'traditional reggae' },
  { name: 'spytrack' },
  { name: 'early music ensemble' },
  { name: 'polka' },
  { name: 'deep freestyle' },
  { name: 'neo soul-jazz' },
  { name: 'deep progressive house' },
  { name: 'contemporary classical' },
  { name: 'electroacoustic improvisation' },
  { name: 'traditional rockabilly' },
  { name: 'halloween' },
  { name: 'clarinet' },
  { name: 'deep jazz piano' },
  { name: 'deep jazz fusion' },
  { name: 'indian rock' },
  { name: 'deep downtempo fusion' },
  { name: 'crossover prog' },
  { name: 'deep classic garage rock' },
  { name: 'experimental dubstep' },
  { name: 'dubstep product' },
  { name: 'football' },
  { name: 'glitch beats' },
  { name: 'skinhead oi' },
  { name: 'polish jazz' },
  { name: 'villancicos' },
  { name: 'deep chill-out' },
  { name: 'deep g funk' },
  { name: 'classic psychedelic rock' },
  { name: 'punk ska' },
  { name: 'deep filthstep' },
  { name: 'deep nordic folk' },
  { name: 'skweee' },
  { name: 'deep northern soul' },
  { name: 'deep pop emo' },
  { name: 'deep hardcore' },
  { name: 'goa trance' },
  { name: 'deep surf music' },
  { name: 'klapa' },
  { name: 'baroque ensemble' },
  { name: 'gamelan' },
  { name: 'deep swedish rock' },
  { name: 'deep thrash metal' },
  { name: 'deep italo disco' },
  { name: 'hatecore' },
  { name: 'demoscene' },
  { name: 'raw black metal' },
  { name: 'hard stoner rock' },
  { name: 'norwegian punk' },
  { name: 'slovenian rock' },
  { name: 'wrock' },
  { name: 'dark progressive house' },
  { name: 'accordeon' },
  { name: 're:techno' },
  { name: 'ambient dub techno' },
  { name: 'neo honky tonk' },
  { name: 'maghreb' },
  { name: 'charred death' },
  { name: 'chill groove' },
  { name: 'breaks' },
  { name: 'kc indie' },
  { name: 'modern downshift' },
  { name: 'vintage swing' },
  { name: 'guitar case' },
  { name: 'tibetan' },
  { name: 'deep punk rock' },
  { name: 'noise' },
  { name: 'deep free jazz' },
  { name: 'deep motown' },
  { name: 'j-punk' },
  { name: 'tanzlmusi' },
  { name: 'italo beats' },
  { name: 'glitter trance' },
  { name: 'malagasy folk' },
  { name: 'lowercase' },
  { name: 'chill-out trance' },
  { name: 'new jack smooth' },
  { name: 'deep nz indie' },
  { name: 'twin cities indie' },
  { name: 'deep eurodance' },
  { name: 'deep power-pop punk' },
  { name: 'grim death metal' },
  { name: 'alternative hardcore' },
  { name: 'deep dub techno' },
  { name: 'j-poppunk' },
  { name: 'deep space rock' },
  { name: 'deep cello' },
  { name: 'vintage rockabilly' },
  { name: 'chinese experimental' },
  { name: 'terrorcore' },
  { name: 'zeuhl' },
  { name: 'doomcore' },
  { name: 'chinese opera' },
  { name: 'indie emo rock' },
  { name: 'french folk' },
  { name: 'jangle rock' },
  { name: 'german street punk' },
  { name: 'nu electro' },
  { name: 'deep hardcore punk' },
  { name: 'rhythm and boogie' },
  { name: 'alternative metalcore' },
  { name: 'ceilidh' },
  { name: 'bulgarian folk' },
  { name: 'modern free jazz' },
  { name: 'thai indie' },
  { name: 'deep neo-synthpop' },
  { name: 'heavy gothic rock' },
  { name: 'ghoststep' },
  { name: 'jazz composition' },
  { name: 'cryptic black metal' },
  { name: 'deep classical piano' },
  { name: 'ethereal gothic' },
  { name: 'deep orgcore' },
  { name: 'vintage schlager' },
  { name: 'swedish jazz orkester' },
  { name: 'song poem' },
  { name: 'vintage country folk' },
  { name: 'gothic doom' },
  { name: 'vintage gospel' },
  { name: 'chip hop' },
  { name: 'deep delta blues' },
  { name: 'deep german jazz' },
  { name: 'twee indie pop' },
  { name: 'dark electro-industrial' },
  { name: 'neo-traditional country' },
  { name: 'cinematic dubstep' },
  { name: 'deep symphonic black metal' },
  { name: 'saxophone' },
  { name: 'deep breakcore' },
  { name: 'anime cv' },
  { name: 'caucasian folk' },
  { name: 'necrogrind' },
  { name: 'deep latin jazz' },
  { name: 'smooth urban r&b' },
  { name: 'vintage swoon' },
  { name: 'central asian folk' },
  { name: 'vintage reggae' },
  { name: 'drone psych' },
  { name: 'deep deep tech house' },
  { name: 'vintage western' },
  { name: 'rock noise' },
  { name: 'deep string quartet' }
]

export default genres
