export const CREATE_INSTRUMENT = 'CREATE_INSTRUMENT';
export const FETCH_INSTRUMENTS = 'FETCH_INSTRUMENTS';
export const FETCH_INSTRUMENT = 'FETCH_INSTRUMENT';
export const EDIT_INSTRUMENT = 'EDIT_INSTRUMENT';
export const DELETE_INSTRUMENT = 'DELETE_INSTRUMENT';
